#!/usr/bin/env python

print "starting recpt1 mock"

import time
from datetime import datetime
import signal
from optparse import OptionParser

# recpt1 [--b25 [--round N] [--strip] [--EMM]]
#        [--udp [--addr hostname --port portnumber]]
#        [--http portnumber] [--device devicefile] [--lnb voltage]
#        [--sid SID1,SID2] channel rectime destfile

parser = OptionParser()
parser.add_option("--b25",   action="store", default=False, dest="b25")
parser.add_option("--strip", action="store", default=False, dest="strip")
parser.add_option("--sid",   action="store", type="string", dest="sid")

(options, args) = parser.parse_args()

if len(args) != 3:
  print "missing arguments!"
  exit(1)

dest = args.pop()
rectime = args.pop()
channel = args.pop()

if rectime != "-":
  print "rectime should be '-'"
  exit(1)

running = True

def shutdown(signum, stack):
  global running
  print "Got signal %s" % signum
  running = False

signal.signal(signal.SIGTERM, shutdown)
signal.signal(signal.SIGINT, shutdown)

f = open(dest, "w")

while running:
  s = "%s\n" % datetime.fromtimestamp(time.time()).strftime("%Y/%m/%d %H:%M:%S")
  f.write(s)
  time.sleep(1)

f.write("\nOK")
f.close()
